name: Makefile CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: |
            ./scripts/install_criterion.sh
            sudo apt-get install -y gcovr
    - name: Build
      run: make
      
    - name: Run test
      run: make tests_run

    - name: Run coverage
      run: make cover
